// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: new-client-service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message when a new client is authenticated and ready to receive data
type NewClientRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientId             string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RoutingKey           string                 `protobuf:"bytes,2,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"` //
	QueueCalibration     string                 `protobuf:"bytes,3,opt,name=queue_calibration,json=queueCalibration,proto3" json:"queue_calibration,omitempty"`
	QueueInterConnection string                 `protobuf:"bytes,4,opt,name=queue_inter_connection,json=queueInterConnection,proto3" json:"queue_inter_connection,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NewClientRequest) Reset() {
	*x = NewClientRequest{}
	mi := &file_new_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewClientRequest) ProtoMessage() {}

func (x *NewClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_new_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewClientRequest.ProtoReflect.Descriptor instead.
func (*NewClientRequest) Descriptor() ([]byte, []int) {
	return file_new_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *NewClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *NewClientRequest) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *NewClientRequest) GetQueueCalibration() string {
	if x != nil {
		return x.QueueCalibration
	}
	return ""
}

func (x *NewClientRequest) GetQueueInterConnection() string {
	if x != nil {
		return x.QueueInterConnection
	}
	return ""
}

// Response message acknowledging the new client notification
type NewClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // Status of the operation (e.g., "OK", "ERROR")
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Optional message or error description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewClientResponse) Reset() {
	*x = NewClientResponse{}
	mi := &file_new_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewClientResponse) ProtoMessage() {}

func (x *NewClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_new_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewClientResponse.ProtoReflect.Descriptor instead.
func (*NewClientResponse) Descriptor() ([]byte, []int) {
	return file_new_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *NewClientResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NewClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_new_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_new_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_new_client_service_proto_rawDescGZIP(), []int{2}
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "SERVING", "NOT_SERVING", "SERVICE_UNKNOWN"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_new_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_new_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_new_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_new_client_service_proto protoreflect.FileDescriptor

const file_new_client_service_proto_rawDesc = "" +
	"\n" +
	"\x18new-client-service.proto\x12\n" +
	"new_client\"\xb3\x01\n" +
	"\x10NewClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vrouting_key\x18\x02 \x01(\tR\n" +
	"routingKey\x12+\n" +
	"\x11queue_calibration\x18\x03 \x01(\tR\x10queueCalibration\x124\n" +
	"\x16queue_inter_connection\x18\x04 \x01(\tR\x14queueInterConnection\"E\n" +
	"\x11NewClientResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbb\x01\n" +
	"\x19ClientNotificationService\x12N\n" +
	"\x0fNotifyNewClient\x12\x1c.new_client.NewClientRequest\x1a\x1d.new_client.NewClientResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.new_client.HealthCheckRequest\x1a\x1f.new_client.HealthCheckResponseB6Z4github.com/mlops-eval/data-dispatcher-service/src/pbb\x06proto3"

var (
	file_new_client_service_proto_rawDescOnce sync.Once
	file_new_client_service_proto_rawDescData []byte
)

func file_new_client_service_proto_rawDescGZIP() []byte {
	file_new_client_service_proto_rawDescOnce.Do(func() {
		file_new_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_new_client_service_proto_rawDesc), len(file_new_client_service_proto_rawDesc)))
	})
	return file_new_client_service_proto_rawDescData
}

var file_new_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_new_client_service_proto_goTypes = []any{
	(*NewClientRequest)(nil),    // 0: new_client.NewClientRequest
	(*NewClientResponse)(nil),   // 1: new_client.NewClientResponse
	(*HealthCheckRequest)(nil),  // 2: new_client.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: new_client.HealthCheckResponse
}
var file_new_client_service_proto_depIdxs = []int32{
	0, // 0: new_client.ClientNotificationService.NotifyNewClient:input_type -> new_client.NewClientRequest
	2, // 1: new_client.ClientNotificationService.HealthCheck:input_type -> new_client.HealthCheckRequest
	1, // 2: new_client.ClientNotificationService.NotifyNewClient:output_type -> new_client.NewClientResponse
	3, // 3: new_client.ClientNotificationService.HealthCheck:output_type -> new_client.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_new_client_service_proto_init() }
func file_new_client_service_proto_init() {
	if File_new_client_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_new_client_service_proto_rawDesc), len(file_new_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_new_client_service_proto_goTypes,
		DependencyIndexes: file_new_client_service_proto_depIdxs,
		MessageInfos:      file_new_client_service_proto_msgTypes,
	}.Build()
	File_new_client_service_proto = out.File
	file_new_client_service_proto_goTypes = nil
	file_new_client_service_proto_depIdxs = nil
}
