// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: new-client-service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientNotificationService_NotifyNewClient_FullMethodName = "/newClient.ClientNotificationService/NotifyNewClient"
	ClientNotificationService_HealthCheck_FullMethodName     = "/newClient.ClientNotificationService/HealthCheck"
)

// ClientNotificationServiceClient is the client API for ClientNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Client Notification service definition
type ClientNotificationServiceClient interface {
	// Notify the service about a new authenticated client that needs data streaming
	NotifyNewClient(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientResponse, error)
	// Health check endpoint
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type clientNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientNotificationServiceClient(cc grpc.ClientConnInterface) ClientNotificationServiceClient {
	return &clientNotificationServiceClient{cc}
}

func (c *clientNotificationServiceClient) NotifyNewClient(ctx context.Context, in *NewClientRequest, opts ...grpc.CallOption) (*NewClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewClientResponse)
	err := c.cc.Invoke(ctx, ClientNotificationService_NotifyNewClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientNotificationServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ClientNotificationService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientNotificationServiceServer is the server API for ClientNotificationService service.
// All implementations must embed UnimplementedClientNotificationServiceServer
// for forward compatibility.
//
// Client Notification service definition
type ClientNotificationServiceServer interface {
	// Notify the service about a new authenticated client that needs data streaming
	NotifyNewClient(context.Context, *NewClientRequest) (*NewClientResponse, error)
	// Health check endpoint
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedClientNotificationServiceServer()
}

// UnimplementedClientNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientNotificationServiceServer struct{}

func (UnimplementedClientNotificationServiceServer) NotifyNewClient(context.Context, *NewClientRequest) (*NewClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyNewClient not implemented")
}
func (UnimplementedClientNotificationServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedClientNotificationServiceServer) mustEmbedUnimplementedClientNotificationServiceServer() {
}
func (UnimplementedClientNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeClientNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientNotificationServiceServer will
// result in compilation errors.
type UnsafeClientNotificationServiceServer interface {
	mustEmbedUnimplementedClientNotificationServiceServer()
}

func RegisterClientNotificationServiceServer(s grpc.ServiceRegistrar, srv ClientNotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientNotificationService_ServiceDesc, srv)
}

func _ClientNotificationService_NotifyNewClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientNotificationServiceServer).NotifyNewClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientNotificationService_NotifyNewClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientNotificationServiceServer).NotifyNewClient(ctx, req.(*NewClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientNotificationService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientNotificationServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientNotificationService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientNotificationServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientNotificationService_ServiceDesc is the grpc.ServiceDesc for ClientNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "newClient.ClientNotificationService",
	HandlerType: (*ClientNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyNewClient",
			Handler:    _ClientNotificationService_NotifyNewClient_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ClientNotificationService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "new-client-service.proto",
}
