// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: data_batch.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataBatchLabeled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Labels        []int32                `protobuf:"varint,2,rep,packed,name=labels,proto3" json:"labels,omitempty"`
	BatchIndex    int32                  `protobuf:"varint,3,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	IsLastBatch   bool                   `protobuf:"varint,4,opt,name=is_last_batch,json=isLastBatch,proto3" json:"is_last_batch,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBatchLabeled) Reset() {
	*x = DataBatchLabeled{}
	mi := &file_data_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBatchLabeled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBatchLabeled) ProtoMessage() {}

func (x *DataBatchLabeled) ProtoReflect() protoreflect.Message {
	mi := &file_data_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBatchLabeled.ProtoReflect.Descriptor instead.
func (*DataBatchLabeled) Descriptor() ([]byte, []int) {
	return file_data_batch_proto_rawDescGZIP(), []int{0}
}

func (x *DataBatchLabeled) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataBatchLabeled) GetLabels() []int32 {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DataBatchLabeled) GetBatchIndex() int32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *DataBatchLabeled) GetIsLastBatch() bool {
	if x != nil {
		return x.IsLastBatch
	}
	return false
}

func (x *DataBatchLabeled) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DataBatchUnlabeled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	BatchIndex    int32                  `protobuf:"varint,2,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`
	IsLastBatch   bool                   `protobuf:"varint,3,opt,name=is_last_batch,json=isLastBatch,proto3" json:"is_last_batch,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataBatchUnlabeled) Reset() {
	*x = DataBatchUnlabeled{}
	mi := &file_data_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataBatchUnlabeled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBatchUnlabeled) ProtoMessage() {}

func (x *DataBatchUnlabeled) ProtoReflect() protoreflect.Message {
	mi := &file_data_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBatchUnlabeled.ProtoReflect.Descriptor instead.
func (*DataBatchUnlabeled) Descriptor() ([]byte, []int) {
	return file_data_batch_proto_rawDescGZIP(), []int{1}
}

func (x *DataBatchUnlabeled) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataBatchUnlabeled) GetBatchIndex() int32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *DataBatchUnlabeled) GetIsLastBatch() bool {
	if x != nil {
		return x.IsLastBatch
	}
	return false
}

func (x *DataBatchUnlabeled) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_data_batch_proto protoreflect.FileDescriptor

const file_data_batch_proto_rawDesc = "" +
	"\n" +
	"\x10data_batch.proto\x12\x02pb\"\xa2\x01\n" +
	"\x10DataBatchLabeled\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\x05R\x06labels\x12\x1f\n" +
	"\vbatch_index\x18\x03 \x01(\x05R\n" +
	"batchIndex\x12\"\n" +
	"\ris_last_batch\x18\x04 \x01(\bR\visLastBatch\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"\x8c\x01\n" +
	"\x12DataBatchUnlabeled\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vbatch_index\x18\x02 \x01(\x05R\n" +
	"batchIndex\x12\"\n" +
	"\ris_last_batch\x18\x03 \x01(\bR\visLastBatch\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionIdB+Z)github.com/data-dispatcher-service/src/pbb\x06proto3"

var (
	file_data_batch_proto_rawDescOnce sync.Once
	file_data_batch_proto_rawDescData []byte
)

func file_data_batch_proto_rawDescGZIP() []byte {
	file_data_batch_proto_rawDescOnce.Do(func() {
		file_data_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_batch_proto_rawDesc), len(file_data_batch_proto_rawDesc)))
	})
	return file_data_batch_proto_rawDescData
}

var file_data_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_batch_proto_goTypes = []any{
	(*DataBatchLabeled)(nil),   // 0: pb.DataBatchLabeled
	(*DataBatchUnlabeled)(nil), // 1: pb.DataBatchUnlabeled
}
var file_data_batch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_batch_proto_init() }
func file_data_batch_proto_init() {
	if File_data_batch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_batch_proto_rawDesc), len(file_data_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_batch_proto_goTypes,
		DependencyIndexes: file_data_batch_proto_depIdxs,
		MessageInfos:      file_data_batch_proto_msgTypes,
	}.Build()
	File_data_batch_proto = out.File
	file_data_batch_proto_goTypes = nil
	file_data_batch_proto_depIdxs = nil
}
